#!/usr/bin/env python3
"""
Analysis script for Multibit Trie performance results.
Reads CSV files generated by the C++ program and creates visualization charts.
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys
import glob
import os

def load_results():
    """Load all results_stride_*.csv files."""
    csv_files = sorted(glob.glob("results_stride_*.csv"))
    
    if not csv_files:
        print("Error: No results_stride_*.csv files found.")
        print("Run the benchmark first to generate results.")
        return None
    
    # Combine all CSV files
    dfs = []
    for f in csv_files:
        df = pd.read_csv(f)
        dfs.append(df)
    
    combined_df = pd.concat(dfs, ignore_index=True)
    return combined_df

def plot_memory_vs_stride(df):
    """Plot memory consumption vs stride."""
    plt.figure(figsize=(10, 6))
    plt.bar(df['stride'], df['estimated_bytes'] / (1024 * 1024), 
            color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728'])
    plt.xlabel('Stride', fontsize=12)
    plt.ylabel('Estimated Memory (MB)', fontsize=12)
    plt.title('Memory Consumption vs Stride', fontsize=14, fontweight='bold')
    plt.grid(axis='y', alpha=0.3)
    plt.xticks(df['stride'])
    
    # Add value labels on bars
    for i, (stride, mem) in enumerate(zip(df['stride'], df['estimated_bytes'] / (1024 * 1024))):
        plt.text(stride, mem, f'{mem:.2f} MB', 
                ha='center', va='bottom', fontsize=10)
    
    plt.tight_layout()
    plt.savefig('memory_vs_stride.png', dpi=300, bbox_inches='tight')
    print("Saved: memory_vs_stride.png")
    plt.close()

def plot_avg_lookup_time_vs_stride(df):
    """Plot average lookup time vs stride."""
    plt.figure(figsize=(10, 6))
    plt.plot(df['stride'], df['avg_ns'], marker='o', linewidth=2, 
             markersize=10, color='#2ca02c')
    plt.xlabel('Stride', fontsize=12)
    plt.ylabel('Average Lookup Time (ns)', fontsize=12)
    plt.title('Average Lookup Time vs Stride', fontsize=14, fontweight='bold')
    plt.grid(alpha=0.3)
    plt.xticks(df['stride'])
    
    # Add value labels
    for stride, avg in zip(df['stride'], df['avg_ns']):
        plt.text(stride, avg, f'{avg:.2f} ns', 
                ha='center', va='bottom', fontsize=10)
    
    plt.tight_layout()
    plt.savefig('avg_lookup_time_vs_stride.png', dpi=300, bbox_inches='tight')
    print("Saved: avg_lookup_time_vs_stride.png")
    plt.close()

def plot_lookup_time_stats(df):
    """Plot min/max/avg with error bars (std)."""
    fig, ax = plt.subplots(figsize=(12, 6))
    
    x = df['stride']
    avg = df['avg_ns']
    std = df['std_ns']
    min_vals = df['min_ns']
    max_vals = df['max_ns']
    
    # Plot average with error bars
    ax.errorbar(x, avg, yerr=std, fmt='o-', linewidth=2, 
                markersize=10, capsize=5, capthick=2, 
                label='Average ± Std Dev', color='#2ca02c')
    
    # Plot min and max
    ax.plot(x, min_vals, 's-', linewidth=1.5, markersize=8, 
            label='Minimum', color='#1f77b4', alpha=0.7)
    ax.plot(x, max_vals, '^-', linewidth=1.5, markersize=8, 
            label='Maximum', color='#d62728', alpha=0.7)
    
    ax.set_xlabel('Stride', fontsize=12)
    ax.set_ylabel('Lookup Time (ns)', fontsize=12)
    ax.set_title('Lookup Time Statistics (Min/Max/Avg ± Std Dev) vs Stride', 
                 fontsize=14, fontweight='bold')
    ax.set_xticks(x)
    ax.grid(alpha=0.3)
    ax.legend(loc='best')
    
    plt.tight_layout()
    plt.savefig('lookup_time_stats.png', dpi=300, bbox_inches='tight')
    print("Saved: lookup_time_stats.png")
    plt.close()

def plot_node_count_vs_stride(df):
    """Plot node count vs stride."""
    plt.figure(figsize=(10, 6))
    plt.bar(df['stride'], df['node_count'], 
            color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728'])
    plt.xlabel('Stride', fontsize=12)
    plt.ylabel('Node Count', fontsize=12)
    plt.title('Number of Nodes vs Stride', fontsize=14, fontweight='bold')
    plt.grid(axis='y', alpha=0.3)
    plt.xticks(df['stride'])
    
    # Add value labels
    for stride, count in zip(df['stride'], df['node_count']):
        plt.text(stride, count, f'{count:,}', 
                ha='center', va='bottom', fontsize=10)
    
    plt.tight_layout()
    plt.savefig('node_count_vs_stride.png', dpi=300, bbox_inches='tight')
    print("Saved: node_count_vs_stride.png")
    plt.close()

def print_summary_table(df):
    """Print a formatted summary table."""
    print("\n" + "="*80)
    print("PERFORMANCE SUMMARY")
    print("="*80)
    print(f"{'Stride':<8} {'Nodes':<12} {'Memory (MB)':<15} {'Avg Time (ns)':<15} {'Std Dev (ns)':<15}")
    print("-"*80)
    
    for _, row in df.iterrows():
        print(f"{int(row['stride']):<8} "
              f"{int(row['node_count']):<12,} "
              f"{row['estimated_bytes']/(1024*1024):<15.2f} "
              f"{row['avg_ns']:<15.2f} "
              f"{row['std_ns']:<15.2f}")
    
    print("="*80 + "\n")

def main():
    """Main analysis function."""
    print("Multibit Trie Performance Analysis")
    print("="*50)
    
    # Load data
    df = load_results()
    if df is None:
        return 1
    
    # Sort by stride
    df = df.sort_values('stride')
    
    # Print summary
    print_summary_table(df)
    
    # Generate plots
    print("Generating charts...")
    plot_memory_vs_stride(df)
    plot_avg_lookup_time_vs_stride(df)
    plot_lookup_time_stats(df)
    plot_node_count_vs_stride(df)
    
    print("\nAnalysis complete! Charts saved as PNG files.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
